config/routes.rb
RentPathApps::Application.routes.draw do
  root :to => 'welcome#index'

  devise_for :users, :controllers => {:registrations => "registrations"}, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  devise_scope :user do
    get "/sign_in",  :to => "devise/sessions#new"
    get "/sign_up",  :to => "devise/registrations#new"
  end

  get 'projects/:id/latestversion' => 'app_versions#latest_version'
  get '/jsHIsh8987HUfhugF1' => 'registrations#new'
  get '/install/:id' => 'app_versions#install'

  resources :users
  resources :token_authentications, :only => [:create, :destroy]
  resources :projects do
    resources :app_versions do
      get 'plist' => 'app_versions#plist'
    end
  end

  delete 'delete_by_version' => 'app_versions#delete_by_version'
  get ":guid" => "app_version#download_link"
end

app/models/app_version.rb
class AppVersion < ActiveRecord::Base
  include Plist

  attr_accessible :name, :version, :url_ipa, :url_plist, :url_icon, :notes, :app_plist, :app_plist_file_name, :app_artifact, :version_icon, :project_id, :created_at, :sha

  def isAndroid?
    file = self.app_artifact_file_name
    file ? file[-4..-1] == ".apk" : nil
  end

  def find_project
    @project ||= Project.find(self.project_id)
  end

  def build_plist(url)
    return if isAndroid?
    return unless find_project

    plist_root = "#{Rails.root}/public/plist"
    plist_template = "#{plist_root}/template.plist"
    plist = Plist::parse_xml(plist_template)

    plist['items'][0]['assets'][0]['url'] = self.app_artifact.url
    plist['items'][0]['metadata']['bundle-identifier'] = find_project.bundle_identifier
    plist['items'][0]['metadata']['bundle-version'] = self.version
    plist['items'][0]['metadata']['title'] = find_project.title

    self.plist_content = plist.to_plist
    self.url_plist = "itms-services://?action=download-manifest&amp;url=#{url}?#{Time.now.to_i.to_s}" 
  end

  has_attached_file :app_artifact,
                    storage: :s3,
                    s3_credentials: {
                        bucket: ENV['AWS_BUCKET'],
                        access_key_id: ENV['AWS_ACCESS_KEY_ID'],
                        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
                    },
                    path: "/:class/:attachment/:id_partition/:style/:filename"

  has_attached_file :version_icon,
                    storage: :s3,
                    s3_credentials: {
                        bucket: ENV['AWS_BUCKET'],
                        access_key_id: ENV['AWS_ACCESS_KEY_ID'],
                        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
                    },
                    styles: { medium: "114x114>",
                                 thumb: "57x57>" },
                    path: "/:class/:attachment/:id_partition/:style/:filename"


  validates :sha, presence: true, uniqueness: {case_sensitive: false, scope: :project_id}

  version_regex =  /\d+.\d+.\d+/

  validates :version,
            presence: true,
            format: {with: version_regex},            
            uniqueness: {case_sensitive: false, scope: :project_id}

  validate :matches_version_for_same_sha

  validates :app_artifact,
            presence: true,
            format: {with: /\.(ipa|apk)/i, message: "Only a .ipa or .apk can be uploaded"}

  validates :version_icon,
            presence: true,
            format: {with: /\.(jpg|png|jpeg)/i, message: "Only a .ipa can be uploaded"}

  def matches_version_for_same_sha
    matching_sha = AppVersion.where(sha: sha).first
    errors.add(:version, "You asked to create version: #{version}, on sha: #{sha}, but we already have \
this version: #{matching_sha.version} for the same sha") unless
    matching_sha.nil? or (matching_sha.version == version)
  end


end

app/controllers/app_versions_controller.rb
class AppVersionsController < ApplicationController
  include AppVersionsHelper
  before_action :set_app_version, only: [:show, :edit, :update, :destroy, :install, :plist]
  before_action :project, only: [:index, :new, :create, :edit, :show, :plist]
  skip_before_filter :verify_authenticity_token
  skip_before_filter :authenticate_user!, only: [:plist]

  def index
    @app_versions     = @project.app_versions
    @android_versions = Array.new
    @ios_versions     = Array.new

    @app_versions.each do |app_version|
      if app_version.app_artifact.url.rindex('.ipa')
        @ios_versions << app_version
      else
        @android_versions << app_version
      end
    end

    @android_versions = @android_versions.sort(&sort_desc(true))
    @ios_versions = @ios_versions.sort(&sort_desc(true))
  end

  def show
    @artifact_url = "/install/#{@app_version.id}"
	  @image_url = 'android.png'
    if @app_version.app_artifact.url.rindex('.ipa')
      @artifact_url = @app_version.url_plist
      @image_url = 'apple.png'
    end
  end

  def install
    require 'net/http'
    require 'open-uri'
    apk_url   = @app_version.app_artifact.url
    project   = Project.find(@app_version.project_id)
    filename  = "#{project.title}-#{@app_version.version}.apk"
    data      = open(apk_url)
    temp_file = File.open data
    headers['Content-Type'] = 'application/vnd.android.package-archive'
    send_file temp_file, :type => 'application/vnd.android.package-archive',
                         :disposition => 'attachment',
                         :filename => filename
  end

  def new
    @app_version = @project.app_versions.new
  end

  def edit
    @app_version = @project.app_versions.find(params[:id])
  end

  def create
    respond_to do |format|
      begin
        @app_version = check_app_version_already_stored(app_version_params)
        unless @app_version
          @app_version = @project.app_versions.create!(app_version_params) 
          @app_version.build_plist(project_app_version_plist_url(@project, @app_version))
          remove_old_builds_for_project(@project)
          @app_version.save!
        end
        format.html { redirect_to "/projects/#{@app_version.project_id}/app_versions/#{@app_version.id}", notice: 'App version was successfully created.' }
        format.json { render action: 'show', status: :created, location: { :saved => true } }
      rescue ActiveRecord::RecordInvalid => e
        format.html { redirect_to edit_project_url(@project, {errors: e.message}) }
        format.json { render json: {error: e.message}, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @app_version.update(app_version_params)
        format.html { redirect_to "/projects/#{@app_version.project_id}/app_versions/#{@app_version.id}", notice: 'App version was successfully updated.' }
        format.mobile { redirect_to "/projects/#{@app_version.project_id}/app_versions/#{@app_version.id}", notice: 'App version was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.mobile { render action: 'edit' }
        format.json { render json: @app_version.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @app_version.destroy
    respond_to do |format|
      format.html { redirect_to "/projects/#{@app_version.project_id}/app_versions/", notice: 'App version(s) was successfully deleted.' }
      format.mobile { redirect_to "/projects/#{@app_version.project_id}/app_versions/", notice: 'App version(s) was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def delete_by_version
    ids = find_by_version.map do |version|
      version.decrement_project_version_if_needed
      version.destroy
      version.id
    end
    render json: {ids: ids}
  end

  def latest_version
    project = Project.find(params[:id])
    app_version = project.app_versions.last
    latest_version = app_version.version
    render :json => { :version => latest_version }
  end

  def plist
    match_timestamp_key ? 
      render({xml: @app_version.plist_content, content_type: 'application/xml'}) : 
      render(json: {result: "auth error"}, status: :unprocessable_entity)
  end

  private

  def set_app_version
    @app_version = AppVersion.find(params[:id] || params[:app_version_id])
  end

  def find_by_version
    return [] unless params[:version]
    AppVersion.where(version: params[:version])
  end

  def app_version_params
    @app_version_params ||= begin
      parse_out_sha
      params[:app_version]
    end
  end

  def project
    begin
      @project ||= Project.find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      render(json: {error: 'could not find project', status: :unprocessable_entity}) unless @project 
    end
  end

  def parse_out_sha
    return if !params[:app_version] or !params[:app_version][:notes]
    notes = params[:app_version][:notes]
    match = notes.match(/([a-f]+|[0-9]+){40}/)
    params[:app_version][:sha] = match[0] if match
  end

  def match_timestamp_key
    @app_version && @app_version.url_plist && (params.keys.member?(@app_version.url_plist.split('?').last))
  end

  def check_app_version_already_stored(app_version_params)
    return if !app_version_params[:sha] or !app_version_params[:version]
    @project.app_versions.where("sha=? and version=?", app_version_params[:sha], app_version_params[:version]).first
  end

end

app/helpers/app_versions_helper.rb
module AppVersionsHelper

  def sort_desc(desc)
    ->(a, b) {

      #if a < b then return  1
      #if a = b then return  0
      #if a > b then return -1

      sort_plus  = (desc) ? 1 : -1
      sort_minus = (desc) ? -1 : 1

      a_version = a.version.sub(/-\w*/, '')
      b_version = b.version.sub(/-\w*/, '')

      return 0 if a_version.equal?(b_version)

      a_array = a_version.split('.')
      b_array = b_version.split('.')

      if a_array.size == b_array.size || a_array.size < b_array.size
        for i in 0..a_array.size
          next if a_array[i].to_i == b_array[i].to_i
          return sort_plus if a_array[i].to_i < b_array[i].to_i
          return sort_minus if a_array[i].to_i > b_array[i].to_i
        end
      elsif a_array.size > b_array.size
        for i in 0..b_array.size
          next if a_array[i].to_i == b_array[i].to_i
          return sort_plus if a_array[i].to_i < b_array[i].to_i
          return sort_minus if a_array[i].to_i > b_array[i].to_i
        end
      end

      a_version <=> b_version
    }
  end

  def notify_users(project)
    User.where.each do |user|
      NotificationMailer.send_notification(user, project).deliver
    end
  end

  def remove_old_builds_for_project(project)
    all_versions = project.app_versions
    ios_versions = Array.new
    android_versions = Array.new
    all_versions.each do |app_version|
      if is_ios(app_version)
        ios_versions << app_version
      else
        android_versions << app_version
      end
    end

    oldest_ios_version = determine_oldest_id_to_keep(ios_versions)
    oldest_android_version = determine_oldest_id_to_keep(android_versions)

    latest_is_ios = is_ios(all_versions.last)
    all_versions.each do |version|
      if latest_is_ios
        version.destroy if is_ios(version) && version.id < oldest_ios_version && ios_versions.count >= 10
      else
        version.destroy if is_android(version) && version.id < oldest_android_version && android_versions.count >= 10
      end
    end
  end

  def determine_oldest_id_to_keep(versions)
    oldest_id = 0
    ids = []
    versions.each do |version|
      ids << version.id
    end
    current_index = 0
    ids = ids.sort {|x,y| y <=> x}
    ids.each do |id|
      oldest_id = id
      current_index = current_index + 1
      return oldest_id if current_index >= 10
    end
    oldest_id
  end

  def is_ios(version)
    (version.app_artifact.url.rindex('.ipa')) ? true : false
  end

  def is_android(version)
    (version.app_artifact.url.rindex('.apk')) ? true : false
  end

end

app/views/app_versions/_form.html.erb
<%= form_for([@project, @app_version]) do |f| %>
  <% if @app_version and @app_version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app_version.errors.count, "error") %> prohibited this app_version from being saved:</h2>

      <ul>
      <% @app_version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>

      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @errors %>
    <div id="error_explanation">
      <h2>An error(s) prohibited this app_version from being saved:</h2>
      <%= @errors %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :notes, :placeholder => 'Notes' %><br  /><p>
    <%= f.text_field :version , :placeholder => 'Version' %><br /><p>
    <%= f.label :app_artifact, 'Application Artifact:' %><br /><p>
    <%= f.file_field :app_artifact %><br /><p>
    <%= f.label :version_icon, 'Application Icon:' %><br /><p>
    <%= f.file_field :version_icon %><br  /><p>
    <%= f.submit 'Submit App Version', :id => 'submitBtnVersion' %>
  </div>

  <div id='loading'><%= image_tag 'spinner.gif' %>Loading... </div>

  <p><%= link_to 'Back', "/projects/#{@app_version.project_id}/app_versions" %></p>
<% end %>

app/views/app_versions/apartments.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>items</key>
    <array>
      <dict>
        <key>assets</key>
        <array>
          <dict>
            <key>kind</key>
            <string>software-package</string>
            <key>url</key>
            <string><%= ipa_path %></string>
          </dict>
          <dict>
            <key>kind</key>
            <string>display-image</string>
            <key>needs-shine</key>
            <true/>
            <key>url</key>
            <string><%= icon_path %></string>
          </dict>
        </array>
        <key>metadata</key>
        <dict>
          <key>bundle-identifier</key>
          <string>com.primedia.Apartments</string>
          <key>bundle-version</key>
          <string><%= version %>></string>
          <key>kind</key>
          <string>software</string>
          <key>title</key>
          <string>Apartments</string>
        </dict>
      </dict>
    </array>
  </dict>
</plist>

app/views/app_versions/edit.html.erb
<h1>Editing app_version</h1>

<%= render 'form' %>

<%= link_to 'Show', "/projects/#{@app_version.project_id}/app_versions/#{@app_version.id}" %> |
<%= link_to 'Back', "/projects/#{@app_version.project_id}/app_versions" %>

app/views/app_versions/index.html.erb
<h1><%= @project.name %> Versions</h1>

<div class="android_builds">
    <table>
      <tbody>
      <% if @android_versions.size > 0 %>
          <% @android_versions.each do |android_version| %>
              <tr>
                <td><%= image_tag 'android.png', width: '50' %></td>
                <td><%= image_tag "#{android_version.version_icon.url(:thumb)}" %></td>
                <td><%= android_version.version %><br/><%= android_version.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%Y at %I:%M%p") %></td>
                <td><%= link_to 'Show', project_app_version_path(@project.id, android_version.id), :class => 'blue_button' %></td>
                <td><%= link_to 'Destroy', "/projects/#{@project.id}/app_versions/#{android_version.id}", method: :delete, data: { confirm: 'Are you sure?' }, :class => 'blue_button'  %></td>
              </tr>
          <% end %>
      <% else %>
          <b>No Android Versions Currently Available.</b>
      <% end %>
      </tbody>
    </table>
</div>

<div class="ios_builds">
    <table>
      <tbody>
        <% if @ios_versions.size > 0 %>
            <% @ios_versions.each do |ios_version| %>
              <tr>
                <td><%= image_tag 'apple.png', width: '50' %></td>
                <td><%= image_tag "#{ios_version.version_icon.url(:thumb)}" %></td>
                <td><%= ios_version.version %><br/><%= ios_version.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%Y at %I:%M%p") %></td>
                <td><%= link_to 'Show', project_app_version_path(@project.id, ios_version.id), :class => 'blue_button' %></td>
                <td><%= link_to 'Destroy', "/projects/#{@project.id}/app_versions/#{ios_version.id}", method: :delete, data: { confirm: 'Are you sure?' }, :class => 'blue_button'  %></td>
              </tr>
            <% end %>
        <% else %>
            <b>No iOS Versions Currently Available.</b>
        <% end %>
      </tbody>
    </table>
</div>

<div class="clear"></div>
<br>

<%= link_to 'New App version', new_project_app_version_path, class: 'blue_button' %>
<p><%= link_to 'Back', '/projects', class: 'blue_button' %></p>

app/views/app_versions/index.mobile.erb
<% title "#{@project.name} Versions" %>

<ul data-role="listview">
  <% @android_versions.each do |android_version| %>
      <li>
        <%= link_to project_app_version_path(@project.id, android_version.id) do %>
            <%= image_tag 'android.png', width: '50' %>
            <%= image_tag "#{android_version.version_icon.url(:thumb)}" %>
            <div>
                <%= android_version.version %><br/><%= android_version.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%Y at %I:%M%p") %>
            </div>
        <% end %>
      </li>
  <% end %>
</ul>

<ul data-role="listview">
  <% @ios_versions.each do |ios_version| %>
      <li>
        <%= link_to project_app_version_path(@project.id, ios_version.id) do %>
            <%= image_tag 'apple.png', width: '50' %>
            <%= image_tag "#{ios_version.version_icon.url(:thumb)}" %>
            <div>
                <%= ios_version.version %><br/><%= ios_version.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%Y at %I:%M%p") %>
            </div>
        <% end %>
      </li>
  <% end %>
</ul>

app/views/app_versions/new.html.erb
<%= render 'form' %>

app/views/app_versions/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Version: <%= @app_version.version %></h2>

<div class="release_content">
    <%= image_tag @image_url, width: '50' %>
    <%= image_tag "#{@app_version.version_icon.url(:thumb)}" %><br/>
    <%= link_to 'Install', @artifact_url, :class => 'blue_button' %><br/>
    <%= link_to 'Download Binary', @app_version.app_artifact.url, :class => 'blue_button'  %><br/>
    <%= link_to 'Back', "/projects/#{@app_version.project_id}/app_versions", :class => 'blue_button' %>
</div>


<div class="release_notes">
    <b><%= @app_version.version %> Release Notes:</b><br/>
    <%= @app_version.notes %>
</div>

<div class="clear"></div>

app/views/app_versions/show.mobile.erb
<% title "#{@app_version.version} " %>
<p id="notice"><%= notice %></p>
<%= image_tag "#{@app_version.version_icon.url(:thumb)}" %>
<%= @app_version.version %>
<p>
  <b><%= @app_version.version %> Release Notes:</b><br/>
  <%= @app_version.notes %>
</p>
<%= link_to 'Install', @artifact_url, 'data-role' => 'button', 'data-ajax' => false %>