config/routes.rb
RentPathApps::Application.routes.draw do
  root :to => 'welcome#index'

  devise_for :users, :controllers => {:registrations => "registrations"}, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  devise_scope :user do
    get "/sign_in",  :to => "devise/sessions#new"
    get "/sign_up",  :to => "devise/registrations#new"
  end

  get 'projects/:id/latestversion' => 'app_versions#latest_version'
  get '/jsHIsh8987HUfhugF1' => 'registrations#new'
  get '/install/:id' => 'app_versions#install'

  resources :users
  resources :token_authentications, :only => [:create, :destroy]
  resources :projects do
    resources :app_versions do
      get 'plist' => 'app_versions#plist'
    end
  end

  delete 'delete_by_version' => 'app_versions#delete_by_version'
  get ":guid" => "app_version#download_link"
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :project_icon, :bundle_identifier, :title
  
  def add_error(field, msg)
    self.errors.add(field, msg)
  end

  has_many :app_versions, dependent: :destroy
  has_attached_file :project_icon,
                    :storage => :s3,
                    :s3_credentials => {
                        :bucket => ENV['AWS_BUCKET'],
                        :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                        :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                    },
                    :styles => { :medium => "114x114>",
                                 :thumb => "57x57>" },
                    :path => "/:class/:attachment/:id_partition/:style/:timestamp/:filename"

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :project, only: [:show, :edit, :update, :destroy]
  before_action :all_projects, only: [:index, :new, :edit]

  def new
    @project = Project.new
  end

  def edit
    @project.add_error('version', params[:errors]) if params[:errors]
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.mobile { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.mobile { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.mobile { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.mobile { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.mobile { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
  def all_projects
    @projects ||= Project.all.sort_by(&:name)
  end

  def project
    @project ||= Project.find(params[:id])
  end

  def project_params
    params[:project]
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :name, :placeholder => 'Project Name (Ex. AG QA)', :size=>50%><br/>
    <%= f.text_field :title, :placeholder => 'Project Title (Ex. Apartments)', :size=>50%><br/>
    <%= f.text_field :bundle_identifier, :placeholder => 'Bundle Identifier', :size=>50%><br/>

    Project Icon: <%= f.file_field :project_icon %><br/><br/> 

    <%= f.submit "Save", style: "margin-top:30px" %>
  </div>
<% end %>

app/views/projects/_form.mobile.erb
<%= form_for(@project) do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="actions">
      <%= f.text_field :name, :placeholder => 'Project Name (Ex. AG QA)', :size=>50%><br/>
      <%= f.text_field :title, :placeholder => 'Project Title (Ex. Apartments)', :size=>50%><br/>
      <%= f.text_field :bundle_identifier, :placeholder => 'Bundle Identifier', :size=>50%><br/>
      <%= f.text_field :running_version_ios, :placeholder => 'iOS Starting Version. Ex. 1.0.0', :size=>50%><br/>
      <%= f.text_field :running_version_android, :placeholder => 'Android Starting Version. Ex. 1.0.0', :size=>50%><br/>
      Project Icon: <%= f.file_field :project_icon %><br/>
      <%= f.submit %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project <%= @project.name %></h1>

<%= render 'form' %>

<%= link_to 'Versions', project_app_versions_path(@project) %> | 
<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/edit.mobile.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project, 'data-role' => 'button' %>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
    <div class="project">
        <%= project.name %><br/>
        <% if project.project_icon.url(:thumb) != '/project_icons/thumb/missing.png' %>
              <%= image_tag "#{project.project_icon.url(:thumb)}" %>
          <% else %>
              <%= image_tag 'rent_path_logo.png', :width => '50' %>
          <% end %>
        <div class="project_links">
            <%= link_to 'Show', "/projects/#{project.id}/app_versions", :class => 'blue_button'%>
            <%= link_to 'Edit', edit_project_path(project), :class => 'blue_button' %>
            <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'blue_button' %>
        </div>
    </div>
<% end %>


<br>

<%= link_to 'New Project', new_project_path, class: 'blue_button' %>

app/views/projects/index.mobile.erb
<% title 'Projects' %>
<% if @projects.size > 0 %>
    <ul data-role="listview">
        <% @projects.each do |project| %>
            <li>
              <%= link_to "/projects/#{project.id}/app_versions" do %>
                <% if project.project_icon.url(:thumb) != '/project_icons/thumb/missing.png' %>
                  <%= image_tag "#{project.project_icon.url(:thumb)}" %>
                <% else %>
                  <%= image_tag 'rent_path_logo.png', :width => '50' %>
                <% end %>
                <%= project.name %>
              <% end %>
            </li>
        <% end %>
    </ul>
<% else %>
    No Projects
<% end %>

<p><%= link_to 'New Project', 'projects/new', 'data-role' => 'button' %></p>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/new.mobile.erb
<h1>New project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%=	 image_tag "#{@project.project_icon.url(:thumb)} " %> <%= @project.name%></h1>
<p><%= link_to 'Versions', "/projects/#{@project.id}/app_versions", :class => 'blue_button' %>
<%= link_to 'Edit', edit_project_path(@project), :class => 'blue_button' %></p>
<p><%= link_to 'Back', projects_path %></p>

app/views/projects/show.mobile.erb
<% title @project.name %>
<h1>
  <% if @project.project_icon.url(:thumb) != '/project_icons/thumb/missing.png' %>
      <%= image_tag "#{@project.project_icon.url(:thumb)}" %>
  <% else %>
      <%= image_tag 'rent_path_logo.png', :width => '50' %>
  <% end %>
  <%= @project.name%>
</h1>
<p>
    <%= link_to 'Versions', "/projects/#{@project.id}/app_versions", 'data-role' => 'button' %>
</p>